<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.1</version>
		<relativePath/>
	</parent>

	<groupId>com.rev</groupId>
	<artifactId>otus</artifactId>
	<version>1.2.0</version>
	<name>otus</name>
	<description>Docker homework: Spring Boot health service</description>
	<url>https://github.com/Evryzh/otus</url>

	<licenses>
		<license>
			<name>MIT License</name>
			<url>https://opensource.org/licenses/MIT</url>
			<distribution>repo</distribution>
			<comments>
				Самая открытая СПО-лицензия: разрешает использование, копирование,
				модификацию, распространение и продажу без ограничений.
			</comments>
		</license>
	</licenses>

	<developers>
		<developer>
			<id>Evryzh</id>
			<name>Евгений Рыжков</name>
			<url>https://github.com/Evryzh</url>
			<roles>
				<role>developer</role>
			</roles>
		</developer>
	</developers>

	<scm>
		<connection>scm:git:https://github.com/Evryzh/otus.git</connection>
		<developerConnection>scm:git:ssh://git@github.com/Evryzh/otus.git</developerConnection>
		<url>https://github.com/Evryzh/otus</url>
		<tag>HEAD</tag>
	</scm>

	<properties>
		<java.version>21</java.version>
	</properties>

	<dependencies>
		<!-- Веб-слой: Spring MVC + встроенный Tomcat + Jackson -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<!-- Actuator: готовый эндпоинт /health -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<!-- Lombok: только для компиляции, в JAR не попадает -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>

		<!-- Тесты -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>