spring:
  application:
    name: otus-users

  http:
    clients:
      connect-timeout: 5s
      read-timeout: 10s

  datasource:
    url: jdbc:postgresql://localhost:5433/otus
    username: otus
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:otus}
          jwk-set-uri: ${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:otus}/protocol/openid-connect/certs

server:
  port: 8000

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.rev.otus: ${LOG_LEVEL:INFO}

management:
  endpoints:
    web:
      base-path: /
  endpoint:
    health:
      show-details: never
      probes:
        enabled: false

springdoc:
  swagger-ui:
    # Включение/отключение Swagger UI
    # Для dev/test обычно true, для prod - false
    enabled: false
  api-docs:
    # Включение/отключение OpenAPI документации
    # Для dev/test обычно true, для prod - false
    enabled: false

keycloak:
  base-url: http://localhost:8080
  realm: otus
  client-id: otus-users
  admin:
    username: admin
    password: ${KEYCLOAK_ADMIN_PASSWORD}