package com.rev.otus.profile;

import com.rev.otus.common.validation.NotBlankIfPresent;
import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Профиль пользователя (таблица customer_profile).<br>
 * Профиль пользователя (бизнес-данные, не аутентификация)
 *
 * <p>ID генерируется автоматически БД (GENERATED BY DEFAULT AS IDENTITY).
 *
 * @author Рыжков Евгений
 * @since 1.0.0
 */
@Entity
@Getter
@Setter
@Builder
@ToString
@DynamicInsert
@DynamicUpdate
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class CustomerProfile {

    @Id
    @Column(updatable = false)
    @Setter(AccessLevel.NONE)
    @EqualsAndHashCode.Include
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @Size(max = 255)
    @Column(nullable = false, unique = true, updatable = false)
    private String keycloakUserId;

    @NotBlank
    @Size(max = 256)
    @Column(nullable = false, unique = true, length = 256)
    private String username;

    @Email
    @NotBlank
    @Size(max = 255)
    @Column(nullable = false, unique = true)
    private String email;

    @Size(max = 20)
    @NotBlankIfPresent
    @Column(unique = true, length = 20)
    private String phone;

    @NotBlank
    @Size(max = 100)
    @Column(nullable = false, length = 100)
    private String firstName;

    @NotBlank
    @Size(max = 100)
    @Column(nullable = false, length = 100)
    private String lastName;

    @Size(max = 100)
    @NotBlankIfPresent
    @Column(length = 100)
    private String middleName;

    private LocalDate birthDate;

    @NotBlank
    @Size(max = 10)
    @Builder.Default
    @Column(nullable = false, length = 10)
    private String preferredLanguage = "ru";

    @NotNull
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @NotNull
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /**
     * Переопределенный toBuilder() всегда обнуляет ID
     * для безопасного создания новых записей на основе существующих.
     */
    public CustomerProfileBuilder toBuilder() {
        return CustomerProfile.builder()
                .id(null)
                .keycloakUserId(this.keycloakUserId)
                .username(this.username)
                .email(this.email)
                .phone(this.phone)
                .firstName(this.firstName)
                .lastName(this.lastName)
                .middleName(this.middleName)
                .birthDate(this.birthDate)
                .preferredLanguage(this.preferredLanguage)
                .createdAt(this.createdAt)
                .updatedAt(this.updatedAt);
    }
}